name: Create Release
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.13.6
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make build test

  semantic-release:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.semantic.outputs.release-version }}
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@v2
      - uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  binary:
    needs: semantic-release
    runs-on: ubuntu-latest
    env:
      VERSION: v${{ needs.semantic-release.outputs.release-version }}
    container:
      image: flanksource/build-tools:v0.13.6
    steps:
      - uses: actions/checkout@v2
      - run: make release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./.bin/*
          tag: v${{ needs.semantic-release.outputs.release-version }}
          overwrite: true
          file_glob: true
